### ISSUE TITLE
Django Girls - March/2019

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/war-room#1]
Django Girls is an international non-profit organization started by two Polish women, Ola Sitarska and Ola Sendecka, to inspire women from all backgrounds to get interested in technology and to become programmers, offering a safe and friendly environment.

We are Planning to host a Django Girls workshop in March of 2019. The event will be lead by Sahyadri Open Source Women's Community (SOSWC)

**Comment by akashdeepb** [comment]
Final Dates ?

**Comment by haxzie-xx** [comment]
Not yet.

**Comment by haxzie-xx** [comment]
We might want to write a post-event report of this event :)

**Comment by haxzie-xx** [comment]
# Post Event Report DjangoGirls Mangaluru - 2019/03/24

We hosted one of the very first DjangoGirls workshops in our city by inviting students from over 5 other colleges. We had a great response from the participants on how they enjoyed learning about modern web development using Django. As the workshop was mainly addressed to encourage the women's in our community, it was one of it's kind and our community has planned to host more similar workshops to encourage girls and women to take part in the future.

## Attendance :dancers:
We had our registrations crossed over 100+ but we had to shortlist and reduce the seats to around 50, so that the workshop will be more interactive :sparkles: . We had 15+ volunteers including mentors to help out the participants during the workshop.

## Venue :school:
Our college had provided the seminar halls for the workshop, which was good enough to hold around 150 students. Since our count was much less, the room was spacious and the entire session was comfortable for the participants and were well relaxed.

## Planning vs Implementation :paperclip:

We had planned for a two day workshop, starting from 23rd with an installation party and 24 th with the actual workshop. But due to exams and time constraints we had to conduct the entire event on 24th, and send out instructions beforehand and open up a communication channel to guide the participants with the installation before a few days of the workshop. We did'nt face any issues due to this. But it was a good experience, and a lesson learned to have a channel open to help the participants meet each other and get to know each other before the workshop.

## Positives :+1:

- All the participants were able to complete the workshop excercises.
- The energy with the attendiees were great! we were showerd with questions and doubts :smile: 
- We were able to kick start our women's community with the help of some of the most talented girls who attended the workshop showing interest to join the community and contribute to it.
- Attendees loved the octocat stickers :heart: 
- There were enough swags and Git Cheat Sheets for all.

## Negatives :-1:
- Due to lack of time our GitHub sponsorship request which we sent through DjangoGirls was rejected.
- Due to lack of resources and sponsorships, we weren't able to provide in house snacks/food for the participants. Anyway our college canteen was kind enough to provide basic meals for lunch :+1:  

## Feedback from Attendees :speech_balloon:

We collected the feedback through Google Forms right at the venue itself. And we had a small session were some of the participants gave feedback directly in the dias.
Few of the responses from the GoogleForms.
![Screenshot_2019-04-03 Django girls Mangaluru](https://user-images.githubusercontent.com/18684321/55471945-8b76a580-5628-11e9-9959-7a36e3da065c.png)

## Social Media Drop 
https://www.instagram.com/p/BvZTGpjFzco/

## Photos 
![IMG-20190324-WA0033](https://user-images.githubusercontent.com/18684321/55472415-adbcf300-5629-11e9-9786-c6fa790da1a7.jpg)
![IMG-20190324-WA0043](https://user-images.githubusercontent.com/18684321/55472417-ae558980-5629-11e9-9e5a-52a2dd8e630f.jpg)
![IMG-20190324-WA0046](https://user-images.githubusercontent.com/18684321/55472421-af86b680-5629-11e9-8ea2-23ed69a3b3a5.jpg)
![IMG_20190324_115101](https://user-images.githubusercontent.com/18684321/55472426-b0b7e380-5629-11e9-9118-14843c7d3d3c.jpg)
![IMG_20190324_100536](https://user-images.githubusercontent.com/18684321/55472430-b31a3d80-5629-11e9-80c7-105631d04aa0.jpg)

## Summary :thought_balloon:

The excecution of the workshop of was really well done by our women's community. They were really hard at work preparing for their very first workshop delivered to the community. The contents and resources helped the participants a lot and we had got a lot of positive feedback. I had chance talk about opensource, version control and how git and GitHub will help throughout their academic and professional career in IT. Overall it was a great event :sparkles: 


<blockquote><img src="https://scontent-iad3-1.cdninstagram.com/vp/1382722d0989e4fc8d3b32ca6b168e23/5D3D0ADC/t51.2885-15/e35/53709453_378775246056631_7326394655963390437_n.jpg?_nc_ht=scontent-iad3-1.cdninstagram.com" width="48" align="right"><div><img src="/static/images/ico/favicon-192.png/68d99ba29cc8.png" height="14"> Instagram</div><div><strong><a href="https://www.instagram.com/p/BvZTGpjFzco/">Sahyadri Open Source Community on Instagram: “It was an amazing day with some of the most talented and enthusiastic girls from our Women's community, #SOSWC taking up the First ever…”</a></strong></div><div>141 Likes, 1 Comments - Sahyadri Open Source Community (@sosc.sahyadri) on Instagram: “It was an amazing day with some of the most talented and enthusiastic girls from our Women's…”</div></blockquote>
