### ISSUE TITLE
JavaScript and Node.js Workshop - 21/04/2019

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/war-room#10]
## JavaScript and Node.js Workshop - 21/04/2019
A full day workshop on Node.js and JavaScript affiliated to NodeSchool. We'll be covering basics of JavaScript on the web and then into serverside development.

## Prerequisites
_check each boxes one by one after completing the tasks, u may check them later by editing the issue too_
- [X] Informed all the SOSC members through whatsapp
- [X] Created an Issue in [SOSC Open-Design](https://github.com/so-sc/open-design) requesting all the graphics assets required for the workshop
- [x] Planned the venue and date for the event
- [x] Collected permissions from concerned faculties and management for venue and event
- [x] Created Registration forms and Feedback forms
- [x] Created an event post in [SOSC website](https://github.com/so-sc/sosc-website)
- [ ] Discussed possible financial requirements with the core memebers

**Comment by AbhiiGatty** [comment]
What topics do we plan to cover and required prerequisite for the people who attend?

**Comment by haxzie-xx** [comment]
How about we divide the workshop into two sessions? The morning session, we'll cover JS on the browser: Basic of HTML and CSS and a small project using JS.
and then, on the afternoon session we'll take Node.js and server-side programming, concepts like NPM and Express.js

**Comment by haxzie-xx** [comment]
Not stale :+1:

**Comment by haxzie-xx** [comment]
So the workshop structure will be as follows.
## Morning session
- Introduction to JavaScript @haxzie  
- History of JavaScript @haxzie 
- Where it is used and current market value/opportunities @haxzie 
- JavaScript on the browser: Introduction @Dhanush-Bangera 
- Managing DOM using JS @shravan1998
- variables, conditional statements, and functions built-in functions @coderhawk999
- Hands-on session on building a small browser-based JS app (Maybe a calculator, weather search, or anything similar) @akashdeepb 

## Afternoon session
- Introduction to Node.js @akashdeepb 
- Introduction to server-side scripting @hm-bilal 
- Javascript Runtime and JavaScript Engines @hm-bilal 
- Introduction to NPM @haxzie 
- Hands-on session - Publishing your first NPM module @haxzie
- Introduction to Express.js @haxzie 
- Building a small web server @haxzie 
## Concluding session
- Node.js and Beyond
- Future of Node
- Frontend frameworks
- opportunities and applications of JS

@AbhiiGatty @coderhawk999 @charmy11 @Dhanush-Bangera @hm-bilal @shravan1998

**Comment by shravan1998** [comment]
Managing DOM using JS
Variables,conditional statements and functions(node)

**Comment by afrzhussain** [comment]
variables, conditional statements, and functions(js)
• built-in functions(js)

**Comment by muhammad-wego** [comment]
Introduction to server-side scripting.
JavaScript on the browser: Introduction

**Comment by akashdeepb** [comment]
Hands-on session on building a small browser based JS app 

Intro to NodeJS

**Comment by dhanushp** [comment]
JavaScript on the browser : Introduction

**Comment by haxzie-xx** [comment]
@hm-bilal You can take up the second and third topics on the Afternoon session. I'll leave the JS on browser to @Dhanush-Bangera instead :+1:

**Comment by haxzie-xx** [comment]
@coderhawk999 @hm-bilal @shravan1998 @Dhanush-Bangera @akashdeepb 

I have updated the Content list with all the speakers. Please confirm.

**Comment by haxzie-xx** [comment]
@coderhawk999 You can use the command line tool built by nodeschool `javascripting` to take up your session. Just complete all the small excercises in it.

https://www.github.com/sethvincent/javascripting

@shravan1998 I'm going to remove the variables and other things from the afternoon session. You can concentrate on the Managing DOM using JS in the morning session

**Comment by haxzie-xx** [comment]
@coderhawk999 @hm-bilal @shravan1998 @Dhanush-Bangera @akashdeepb

Please update here, the topics you are going to cover and things you have prepared here. ie. topics which comes under the main topics I have mentioned here.

**Comment by shravan1998** [comment]
Properties of DOM
Events
Event listeners

**Comment by haxzie-xx** [comment]
Good Job Boys!
