### ISSUE TITLE
Flutter Sprint

### ISSUE THREAD

**Issue by ShreyasBaliga** [so-sc/war-room#15]
# Flutter Sprint | 29 Sep 2019, 6 Oct 2019, 11 Oct 2019

### Abstract
An introductory series of workshops on Flutter and DartLang.

## Prerequisites

- [x] Informed all the SOSC members through whatsapp
- [x] Created an Issue in [SOSC Open-Design](https://github.com/so-sc/open-design) requesting all the graphics assets required for the workshop
- [x] Planned the venue and date for the event
- [x] Collected permissions from concerned faculties and management for venue and event
- [x] Created Registration forms and Feedback forms
- [x] Created an event post in [SOSC website](https://github.com/so-sc/sosc-website)

**Comment by melwinlobo18** [comment]
# Flutter 101
Event Date: 29-09-2019

### Topics to be covered

####  Morning Session (10:30 - 1:00)
- Introduction to Flutter & Dart
- Stateful and Stateless Widgets
- Basic Flutter app (Structure of the code)

#### Afternoon Session (2:00 - 5:00)
- Flutter widgets

    Mi Card (Flutter App)
    - Scaffold
    - Container
    - ListTile
        - Card
        - Text
        - Icon
    - Column
    - Row

**Comment by rumaan** [comment]
That's great!
Since Scaffold and Container are pretty basic widgets, how about replacing those with some fundamental ones like explaining about **stateful and stateless widgets** and a simple example of **setState** along with on-click of a button.  😇

@melwinlobo18 @ShreyasBaliga

**Comment by ekokratos** [comment]
@rumaan we'll be conducting two workshops. We thought of covering all the basic widgets in the first workshop and introducing stateful widget in the second one.

**Comment by rumaan** [comment]
Ah, that's great! All the best. Just make sure students have flutter installed and setup beforehand.

**Comment by ekokratos** [comment]
Even after we mention in prerequisites to install Flutter many won't do it. That's the only thing I'm concerned about. 😅

**Comment by akshayrb22** [comment]
Maybe we could include blog post guides and YouTube links on how to do it. We will have to be ready when few people come without it installed though.

**Comment by akshayrb22** [comment]
Design details are mentioned here:
https://github.com/so-sc/open-design/issues/12

**Comment by shreyapy** [comment]
The idea is very good guys!!
should focus more on Widgets I guess...coz rest of them are pretty basic I guess :)

**Comment by dhanushp** [comment]
Where's the venue and is it associated with DSC?

**Comment by akshayrb22** [comment]
Yes, it is associated with DSC. So we will need the general style to be similar. As for the date and venue... We are unsure due to some clashes with the placement department. We'll let you know pretty soon.

**Comment by akshayrb22** [comment]
We have updated the date so as to ensure that it does not clash with the college placement activities.

**Comment by dhanushp** [comment]
Okay, just confirm the venue also :)

**Comment by akshayrb22** [comment]
Confirmed the venue @dhanushp . It's going to be held at the 2nd floor seminar hall.

**Comment by akshayrb22** [comment]
Alright! We had Flutter 101 with a reasonable amount of success, the only downside being the installation issues. Maybe we should consider dealing with that 1 day before... Or we could have kept a separate day for that. Either way, let's discuss the topics to be taken up for the next workshop. @ekokratos and @melwinlobo18  can we have the details of the next workshop by 02/10/2019?

**Comment by melwinlobo18** [comment]
# Flutter 201
Event Date: 06-10-2019
Timings: 10:30 - 5:00

#### Instructors
@melwinlobo18 @ekokratos 

### Topics to be covered

#### BMI Calculator

- Navigation
- Flare Animations
- Flutter Themes
- Code Refactor
- Dart data types & operators
- Custom Widgets

**Comment by melwinlobo18** [comment]
## Prerequisites

- [ ] Informed all the SOSC members through WhatsApp
- [x] Created an Issue in [SOSC Open-Design](https://github.com/so-sc/open-design) requesting all the graphics assets required for the workshop
- [x] Planned the venue and date for the event
- [x] Collected permissions from concerned faculties and management for venue and event
- [ ] Created Registration forms and Feedback forms
- [ ] Created an event post in [SOSC website](https://github.com/so-sc/sosc-website)
- [x] Requested for internet connection

**Comment by melwinlobo18** [comment]
# Flutter 301
Event Date: 11-10-2019
Timings: 10:30 - 5:00

#### Instructors
Nikita Gandhi

### Topics to be covered

#### Chat App

- Dart Futures, Async and Await
- Exception Handling
- Firebase Project Setup
- Firebase Auth
- Saving data into Cloud Firestore
- Listening data through Streams
- StreamBuilder

**Comment by ekokratos** [comment]
> # Flutter 201
> Event Date: 05-10-2019
> Timings: 10:30 - 5:00
> 
> #### Instructors
> @melwinlobo18 @ekokratos
> 
> ### Topics to be covered
> #### BMI Calculator
> * Navigation
> * Flare Animations
> * Flutter Themes
> * Code Refactor
> * Dart data types & operators
> * Custom Widgets

Do we need Flare animation? Instead we can include Hero animation and custom in-built animation. (Like in the homepage of Flash Chat app)

**Comment by melwinlobo18** [comment]
> > # Flutter 201
> > Event Date: 05-10-2019
> > Timings: 10:30 - 5:00
> > #### Instructors
> > @melwinlobo18 @ekokratos
> > ### Topics to be covered
> > #### BMI Calculator
> > 
> > * Navigation
> > * Flare Animations
> > * Flutter Themes
> > * Code Refactor
> > * Dart data types & operators
> > * Custom Widgets
> 
> Do we need Flare animation? Instead we can include Hero animation and custom in-built animation. (Like in the homepage of Flash Chat app)

We'll keep it at the end. If we have time then we'll take it.
