### ISSUE TITLE
Explore ML Workshop Series

### ISSUE THREAD

**Issue by suhanacharya** [so-sc/war-room#18]
__Abstract__ 

Explore Machine Learning is an introductory Workshop for ML and Neural Networks. 
Its going to be a series of multiple workshops or multiple hours of workshop spanning for two days
(need not be consecutive days - once a week will do)

__Prerequisites__
---
Check each boxes one by one after completing the tasks, u may check them later by editing the issue too

- [x] Informed all the SOSC members through Whatsapp
 - [x] Planned the venue and date for the event
- [x] Venue : IS Lab V, Room 219, SCEM
- [x] Date : 22/02/2020
 - [x] Collected permissions from concerned faculties and management for venue and event
 - [x] Created Registration forms and Feedback forms
 - [x] Created an event post in SOSC website
 - [x] Created/Updated Event Social Media Handles

**Comment by suhanacharya** [comment]
@akshayrb22 What's the next step?

**Comment by akshayrb22** [comment]
@suhanacharya  The problem is that the last month of the semester usually has students a lot busier in labs and other such activities. It becomes a little tough to manage an event and have an audience for it. Does ExploreML have to be held by the end of this year? Or can we have it in the next semester?

**Comment by suhanacharya** [comment]
@akshayrb22 The planned time window for Explore ML is Sept-Dec. But I was told it was possible to do it later.

**Comment by akshayrb22** [comment]
If it's possible to move it up let's do that. The start of a semester is relatively free. It becomes a lot easier to get things moving.
