### ISSUE TITLE
DevHost:19 - 28-29 Sept 2019

### ISSUE THREAD

**Issue by haxzie-xx** [so-sc/war-room#2]
Devhost 19 will be the second annual flagship event of SOSC. It was a success during the last year and making changes to the previous year's plans, we are planning to bring in student speakers to completely make it as a Student Developer's conference.

**Comment by haxzie-xx** [comment]
@so-sc/webdev Guys, we gotta start building the website for DevHost:19 to start looking for sponsors. Keep this issue open for discussion and the main thing is which framework you guys would like to use. I'd recommend Vue.js or Gatsby since it'll help ya all to learn something new. Drop down the suggestions, we gotta complete this before February start.

**Comment by shravan1998** [comment]
Someone needs to get the design first cuz you know....for an idea

**Comment by haxzie-xx** [comment]
Basically, the event will be of 2 days. 1st day for conference/talks second day starting from 1st day night will be a general hackathon.
- We gotta find speakers, and topics (preferably students or community leads from other colleges)
- Hackathon theme and sponsorships

**Comment by shravan1998** [comment]
And just like the other websites we've made we can keep a timer there too and besides that on the footer we ask the sponsors to contact us

**Comment by shravan1998** [comment]
We can create another page though specifically for the events taking place

**Comment by akashdeepb** [comment]
@shravan1998 I guess we do have that on our current website, events occured and upcoming events

**Comment by haxzie-xx** [comment]
> @shravan1998 I guess we do have that on our current website, events occured and upcoming events

@akashdeepb We might need  new website for everything related to DevHost

**Comment by haxzie-xx** [comment]
Not stale :)

**Comment by akashdeepb** [comment]
Updated Date : 07-08 Sept 2019

**Comment by akshayrb22** [comment]
@akashdeepb Any updates?
