### ISSUE TITLE
Quantum Computing

### ISSUE THREAD

**Issue by Basavarajeshwari-Ambi** [so-sc/war-room#27]
**
Quantum Computing - Why should you be excited about it? | 26/06/2021
*### Abstact*
One of the most promising new trends in both physics and computer science, join us in this introductory kick off session of SoSC's new Quantum Division SoSC - |Q> where we explore and shed light upon why you should care about this new paradigm of computation that can have promising industrial applications in various fields across the technological spectrum including, but not restricted to Cybersecurity, Drug Development, Financial Modeling, Artificial Intelligence & Machine Learning to name a few.
*Goals to be achieved from the workshop*
- Create awareness about quantum technologies and computing and how people can incorporate in their current field of study
- Set expectations as to where quantum computations can and cannot be useful
- Sow an initial seed of thought about the possibilities of using this technology and offer further learning resources of learning pathways to go forward in this field

## Prerequisites
_check each boxes one by one after completing the tasks, u may check them later by editing the issue too_
- [ ] Informed all the SOSC members through whatsapp
- [ ] Created an Issue in [SOSC Open-Design](https://github.com/so-sc/open-design) requesting all the graphics assets required for the workshop
- [ ] Planned the venue and date for the event
- [ ] Collected permissions from concerned faculties and management for venue and event
- [ ] Created Registration forms and Feedback forms
- [ ] Created an event post in [SOSC website](https://github.com/so-sc/sosc-website)
- [ ] Discussed possible financial requirements with the core memebers

**Comment by suhanacharya** [comment]
@Basavarajeshwari-Ambi Completed!
