### ISSUE TITLE
Hacktoberfest Mid Event Games (Internal/Community Hackathon) - TBD

### ISSUE THREAD

**Issue by suhanacharya** [so-sc/war-room#28]
## HackSOSC Minigames 🎮 Internal(Or Open Community) Hackathon - 06/07/2021

We build Mini games to be played in between Hacktoberfest hackathon or future events preferably competitive, multiplayer.

Rules:
- Team size 1-3 people 👩👨🧑
- All games should be web-based and lite quick games ⏩⏩
  - Examples: 
    - https://skribbl.io/ - Draw and guessing
    - https://garticphone.com/ - Draw, guessing, drawing version of Chinese Whisper
    - https://www.google.com/doodles/halloween-2018 - Multiplayer mini game
- No Copyrights only (Don't use copyright music or branding)

Prizes? No, prizes as such, if it's good, we'll play them at events credits to creator, maybe some swags.

## Prerequisites
- [x] Informed all the SOSC members through Whatsapp
- [x] Planned the venue and date for the event
  - **Venue : Online**
  - **Date  : 06/07/2021 - 13/07/2021**
- [x] Created Registration forms and Feedback forms

**Comment by suhanacharya** [comment]
@akashdeepb What do you think?

**Comment by akashdeepb** [comment]
Sounds Sick :sparkler: Gonna make em juniors cry
