### ISSUE TITLE
Cloud Study Jam - August 2019

### ISSUE THREAD

**Issue by akshayrb22** [so-sc/war-room#4]

**Comment by akashdeepb** [comment]
Any updates on this?

**Comment by akshayrb22** [comment]
Yes... We plan to host it within the first few weeks of college. The prerequisites are that the trainers know the crash course.

**Comment by akshayrb22** [comment]
I will chart out a plan and update it here within the next 2 days.

**Comment by haxzie-xx** [comment]
Any update on this @akshayrb22 ?

**Comment by akshayrb22** [comment]
I think we'll have to put it on hold for now. Seeing as our next workshop is around the end of April, and the fact that we will not have attendees during the final leg of the semester(3rd internals and all that), I feel it's best to push this to the next semester.

**Comment by akshayrb22** [comment]
I think it's best to close this issue as we won't be holding another event apart from the Fundamentals of Cloud workshop #9 during this semester. Maybe we could reopen it next semester.

**Comment by akashdeepb** [comment]
Conducting on 17/08/2019

**Comment by akshayrb22** [comment]
# Cloud Study Jam- 17th August 2019

Session to bring about awareness of Cloud Technologies available through the Google Cloud Platform and to familiarize them with the working of these technologies.

# Prerequisites

- [x] Informed all the SOSC members through WhatsApp
- [x] Decide on all topics to be covered
- [x] Created an Issue in SOSC Open-Design requesting all the graphics assets required for the workshop
- [x] Planned the venue and date for the event
- [x] Collected permissions from concerned faculties and management for venue and event
- [x] Created Registration forms and Feedback forms
- [ ] Created an event post in SOSC website

**Comment by akshayrb22** [comment]
I was thinking we could do this session during the 3rd week of August, i.e. on 17/08/2019. What do you guys think @ShreyasBaliga, @akashdeepb, @melwinlobo18, @gauthami26, @coderhawk999?

**Comment by akshayrb22** [comment]
@melwinlobo18  Any ideas on the topics we have to cover? Let me know at the earliest.

**Comment by melwinlobo18** [comment]
Morning Session
**GCP Essentials (Quest)**
@melwinlobo18 
- A Tour of Qwiklabs and the Google Cloud Platform
- Creating a Virtual Machine
- Getting Started with Cloud Shell & gcloud
- Kubernetes Engine: Qwik Start

Afternoon Session
**Baseline: Data, ML, AI (Quest)**
@ShreyasBaliga 
- Cloud ML Engine: Qwik Start
- Google Cloud Language/Speech/Video Intelligence API

**Comment by akshayrb22** [comment]
Not stale. :+1:

**Comment by akshayrb22** [comment]
@gauthami26 Please take a count of the number of attendees and the gender demographic for the DSC event form on the day of the event. Also, prep a summary of the event. We can fine tune it and send it to the Buzz through here.
