### ISSUE TITLE
DSC Workshop - 30/31 March 2019

### ISSUE THREAD

**Issue by akashdeepb** [so-sc/war-room#6]
Workshop related to either of 3 major topic (PWA, Android, ML). To be decided based on RESPONSE from students.
Check the Below once Done

- [X] Permissions for Event
- [x] Finalizing Event Topic
- [x] Declaring and Sharing Workshop details 
- [x] Pre Requisites Check
- [x] Post Event Report

**Comment by akshayrb22** [comment]
Based on the votes, we have decided to take up Android. We need to help install Android for all the participants. That can be done on a daily basis.

**Comment by haxzie-xx** [comment]
Awesome! I have got more students reaching out to me regarding the registrations now :)

**Comment by akshayrb22** [comment]
Event conducted successfully. Post-event report made and sent to Sahyadri Buzz.
