### ISSUE TITLE
Step to the new world! AR/VR Workshop - 06/04/2019

### ISSUE THREAD

**Issue by Basavarajeshwari-Ambi** [so-sc/war-room#7]
## Step to the new world! - 6th April 2019

Introductory Workshop about VR,AR,VR Headsets,Tilt Brush,Jump,Blocks all latest tech connected to 3D world of design.

## Prerequisites
_check each boxes one by one after completing the tasks, u may check them later by editing the issue too_
- [x] Informed all the SOSC members through whatsapp
- [x] Created an Issue in [SOSC Open-Design](https://github.com/so-sc/open-design) requesting all the graphics assets required for the workshop
- [x] Planned the venue and date for the event
- [x] Collected permissions from concerned faculties and management for venue and event
- [x] Created Registration forms and Feedback forms
- [x] Created an event post in [SOSC website](https://github.com/so-sc/sosc-website)
- [x] Discussed possible financial requirements with the core memebers

**Comment by haxzie-xx** [comment]
@so-sc/mozilla-campus-club it'd be great if you guys can update the post in the website with a post-event-report. You can refer an example from our previous event https://sosc.org.in/events/DjangoGirls19
